# Generated by Django 4.2.15 on 2026-01-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/hujjat/'),
        ),
    ]
