# Generated by Django 4.2.15 on 2026-05-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0002_alter_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Infodata',
        ),
        migrations.DeleteModel(
            name='Qabriston',
        ),
    ]
