# Generated by Django 4.2.15 on 2026-03-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="flower",
        ),
    ]
