services:
  jazzmin-web:
    build: .
    container_name: jazzmin-web
    ports:
      - "8009:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - START_BOT=0
    depends_on:
      - jazzmin-db
    networks:
      - jazzmin_network
    command: python manage.py runserver 0.0.0.0:8000

  jazzmin-bot:
    build: .
    container_name: jazzmin-bot
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - jazzmin-db
    networks:
      - jazzmin_network
    restart: unless-stopped
    command: python bot_main.py

  jazzmin-db:
    image: postgres:15
    container_name: jazzmin-db
    env_file:
      - .env
    volumes:
      - jazzmin_postgres_data:/var/lib/postgresql/data
    networks:
      - jazzmin_network

volumes:
  jazzmin_postgres_data:

networks:
  jazzmin_network:
    driver: bridge
