version: '3.8'

services:
  jazzmin-web:
    build: .
    ports:
      - "8008:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - intranet
      - dressme_extranet
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - intranet

volumes:
  postgres_data:

networks:
  intranet:
    driver: bridge
  dressme_extranet:
    external: true
