# Generated by Django 4.2.15 on 2026-03-18 04:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("botapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogFlowerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=200, verbose_name="Nomi (UZ)")),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Название (RU)"),
                ),
                ("name_en", models.CharField(max_length=200, verbose_name="Name (EN)")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faol / Active"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tartib / Order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Flower Category",
                "verbose_name_plural": "Flower Categories",
                "ordering": ["sort_order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="CatalogService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=200, verbose_name="Nomi (UZ)")),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Название (RU)"),
                ),
                ("name_en", models.CharField(max_length=200, verbose_name="Name (EN)")),
                (
                    "description_uz",
                    models.TextField(
                        blank=True, default="", verbose_name="Tavsif (UZ)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, default="", verbose_name="Описание (RU)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, default="", verbose_name="Description (EN)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Narx / Price",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cleaning", "Cleaning / Tozalash"),
                            ("flowers", "Flowers / Gullar"),
                            ("renewal", "Renewal / Yangilash"),
                            ("other", "Other / Boshqa"),
                        ],
                        default="cleaning",
                        max_length=30,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faol / Active"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Rasm / Image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["category", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="CatalogFlowerProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=200, verbose_name="Nomi (UZ)")),
                (
                    "name_ru",
                    models.CharField(max_length=200, verbose_name="Название (RU)"),
                ),
                ("name_en", models.CharField(max_length=200, verbose_name="Name (EN)")),
                (
                    "description_uz",
                    models.TextField(
                        blank=True, default="", verbose_name="Tavsif (UZ)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, default="", verbose_name="Описание (RU)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, default="", verbose_name="Description (EN)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Narx / Price",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faol / Active"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="flowers/",
                        verbose_name="Rasm / Image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="botapp.catalogflowercategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flower Product",
                "verbose_name_plural": "Flower Products",
                "ordering": ["category", "name_en"],
            },
        ),
    ]
