# Generated by Django 4.2.15 on 2026-03-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("botapp", "0004_add_flower_planting_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="full_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Ism / Full Name"
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="phone_number",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Telefon / Phone"
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="username",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Telegram username"
            ),
        ),
    ]
