# Generated by Django 4.2.15 on 2026-03-24 20:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("botapp", "0005_add_profile_fields_to_telegramuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerServiceFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        help_text="Masalan: Tozalash, Gul ekish, Yetkazib berish",
                        max_length=200,
                        unique=True,
                        verbose_name="Hizmat nomi / Service name",
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ishchiga to'lanadigan summa (so'm)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="To'lov summasi / Fee amount",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Qo'shimcha ma'lumot",
                        verbose_name="Tavsif / Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faol / Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ishchi Hizmat To'lovi",
                "verbose_name_plural": "Ishchi Hizmat To'lovlari",
                "ordering": ["service_name"],
            },
        ),
    ]
