# Generated by Django 4.2.15 on 2026-03-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("botapp", "0006_add_worker_service_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogflowerproduct",
            name="category",
        ),
        migrations.DeleteModel(
            name="CatalogFlowerCategory",
        ),
        migrations.DeleteModel(
            name="CatalogFlowerProduct",
        ),
    ]
