# Generated by Django 4.2.15 on 2025-08-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0005_profile_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
