# Generated by Django 4.2.15 on 2026-05-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0006_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qabristonmap',
            name='product',
        ),
        migrations.RemoveField(
            model_name='qabristonmap_image',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Qabristonmap',
        ),
        migrations.DeleteModel(
            name='Qabristonmap_image',
        ),
    ]
