# Generated by Django 5.1.4 on 2025-01-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desnoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(blank=True, max_length=20)),
                ('surname', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('patronymic', models.CharField(blank=True, max_length=20)),
                ('data_of_birth', models.DateField(blank=True, max_length=20)),
                ('cart_number', models.CharField(blank=True, max_length=20)),
                ('personal_number', models.CharField(blank=True, max_length=20)),
                ('mahalla_id', models.CharField(blank=True, max_length=20)),
                ('mahalla_name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(blank=True, max_length=20)),
                ('surname', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('patronymic', models.CharField(blank=True, max_length=20)),
                ('data_of_birth', models.CharField(blank=True, max_length=20)),
                ('cart_number', models.CharField(blank=True, max_length=20)),
                ('personal_number', models.CharField(blank=True, max_length=20)),
                ('cart_number_p', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
