# Generated by Django 4.2.15 on 2026-05-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotGrave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Tuman')),
                ('cemetery', models.CharField(blank=True, max_length=200, verbose_name='Qabriston')),
                ('deceased_full_name', models.CharField(blank=True, max_length=200, verbose_name='Marhum')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name="Tug'ilgan yili")),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Vafot yili')),
                ('birth_approximate', models.BooleanField(default=False, verbose_name="Tug'ilish taxminiy")),
                ('death_approximate', models.BooleanField(default=False, verbose_name='Vafot taxminiy')),
                ('relationship_status', models.CharField(blank=True, max_length=50, verbose_name='Qarindoshlik')),
            ],
            options={
                'verbose_name': 'Qabr',
                'verbose_name_plural': 'Qabrlar',
                'db_table': 'graves',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BotOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Ism-familiya')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('deceased_full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marhum')),
                ('total_price', models.IntegerField(default=0, verbose_name='Summa')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Holat')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name="To'lov usuli")),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Sana')),
                ('assigned_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ishchi')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan')),
                ('feedback', models.CharField(blank=True, max_length=20, null=True, verbose_name='Baho')),
                ('feedback_reason', models.TextField(blank=True, null=True, verbose_name='Baho izohi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'orders',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BotOrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(blank=True, max_length=30, verbose_name='Turi')),
                ('item_id', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Nomi')),
                ('quantity', models.IntegerField(default=1, verbose_name='Soni')),
                ('price', models.IntegerField(default=0, verbose_name='Narxi')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Ism-familiya')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('language', models.CharField(blank=True, max_length=5, verbose_name='Til')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxatdan o'tgan sana")),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
