server {
    listen 80;

    server_name mas-kan.uz www.mas-kan.uz;

    location /static/ {
        alias /app/staticfiles/;
        expires 7d;
        access_log off;
    }

    location /media/ {
        alias /app/media/;
        expires 7d;
        access_log off;
    }

    location / {
        proxy_pass http://jazzmin-web:8000;
        # ❗ ENG MUHIM:
        # 👉 "jazzmin-web" = docker-compose dagi service nomi
        # 👉 8000 = container ichidagi port (8008 emas!)

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_redirect off;
    }

    # ❗ Django static bo‘lsa:
    # location /static/ {
    #     alias /app/static/;
    # }

    # ❗ Django media bo‘lsa:
    # location /media/ {
    #     alias /app/media/;
    # }
}
