server {
    listen 80;
    server_name mas-kan.uz www.mas-kan.uz;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
