"""
Centralized text messages. Languages: en, ru, uz.
"""
from typing import Any

TEXTS: dict[str, dict[str, str]] = {
    "en": {
        # Start / Welcome
        "welcome": "Welcome to the Grave Care Service.\nPlease select your language:",
        "welcome_short": "🪦 <b>ADD GRAVE</b>\n\nEnter information about your deceased loved one below.\nThis information is needed to place an order.",
        "welcome_back": "Hello, {name}! Welcome back. Choose a service from the menu below.",
        "choose_language": "Please choose your language:",
        "language_selected": "Language selected.",
        "btn_change_language": "Change Language",
        "registration_required": "👋 Welcome!\n\nEnter your name:",
        "registration_phone": "Now share your phone number (tap the button or type it):",
        "registration_complete": "✅ Thank you, {name}!\n\n🪦 Now add the grave you want to care for:",
        "add_grave_first": "Please add the grave you want to clean first.",
        "profile_saved": "Profile saved.",
        "main_menu": "Main menu",
        # Profile
        "enter_full_name": "Enter your full name:",
        "enter_phone": "Share your phone number (tap the button):",
        "invalid_name": "Name must be at least 2 characters. Try again.",
        "invalid_phone": "Invalid phone number. Try again.",
        "my_profile": "📋 Your profile:\n\nName: {full_name}\nPhone: {phone_number}\nLanguage: {language}",
        "profile_graves_title": "Saved graves:",
        "profile_graves_empty": "No graves saved yet.",
        "profile_grave_item": "{num}. {name}\n   Relationship: {relationship}\n   Cemetery: {cemetery}\n   Birth: {birth} | Death: {death}",
        "grave_enter_region": "Select region:",
        "grave_enter_district": "Select district:",
        "grave_enter_cemetery": "Select cemetery:",
        "grave_enter_deceased": "Enter deceased full name:",
        "grave_enter_birth_choice": "Birth date — exact or approximate?",
        "grave_enter_birth_year": "Enter birth year (4 digits, e.g. 1950):",
        "grave_enter_birth_year_only": "Enter birth year only (4 digits, e.g. 1950):",
        "grave_enter_birth_month": "Enter birth month (1-12):",
        "grave_enter_death_choice": "Death date — exact or approximate?",
        "grave_dates_choice": "Are the birth and death dates exact?",
        "grave_enter_death_year": "Enter death year (4 digits, e.g. 2020):",
        "grave_enter_death_year_only": "Enter death year only (4 digits, e.g. 2020):",
        "grave_enter_death_month": "Enter death month (1-12):",
        "grave_enter_relationship": "Select relationship:",
        "grave_invalid_month": "Enter a valid month (1-12).",
        "btn_exact": "Exact",
        "btn_approximate": "Approximate",
        "grave_added": "Grave added successfully.",
        "grave_cancelled": "Cancelled.",
        "my_graves_title": "Your saved graves:",
        "my_graves_empty": "You have no saved graves yet. Use Add Grave to add one.",
        "btn_view_profile": "View Profile",
        "btn_update_profile": "Update Profile",
        # Main menu buttons
        "btn_services": "Services",
        "btn_flowers": "Flowers",
        "btn_cart": "Cart",
        "btn_profile": "Profile",
        "btn_share_phone": "📱 Share Phone",
        "btn_order_history": "Order History",
        "btn_subscriptions": "Subscriptions",
        "btn_complaints": "Complaints & Suggestions",
        "btn_support": "Contact Support",
        "btn_rating": "Rate Work",
        "btn_about": "About Us",
        "btn_back": "⬅️ Back",
        "btn_cancel": "❌ Cancel",
        "btn_skip": "Skip",
        "btn_add_grave": "Add Grave",
        "btn_my_graves": "My Graves",
        "btn_main_menu": "◀️ Main Menu",
        # Services
        "services_title": "Our Services",
        "btn_cleaning": "Cleaning",
        "btn_basic_cleaning": "Basic Cleaning",
        "btn_deep_cleaning": "Deep Cleaning",
        "btn_full_maintenance": "Full Maintenance",
        "btn_plant_flowers": "Plant Flowers",
        "btn_watering_service": "Watering Service",
        "btn_seasonal_care": "Seasonal Care",
        "section_grave_cleaning": "Grave Cleaning",
        "section_flowers": "Flowers",
        "section_grave_renewal": "Grave Renewal",
        "flower_catalog": "Flower catalog",
        "flower_menu_title": "🌸 Flowers Menu",
        "flower_category_planted": "Flowers planted around the grave",
        "flower_category_placed": "Flowers placed on the grave",
        "flower_order_first_name": "Enter first name:",
        "flower_order_last_name": "Enter last name:",
        "flower_order_birth_year": "Enter birth year (4 digits, e.g. 1950):",
        "flower_order_death_year": "Enter death year (4 digits, e.g. 2020):",
        "flower_confirm_summary": "Items:\n{items}\n\nTotal: {total}",
        "flower_proceed_to_payment": "Proceed to Payment",
        "flower_item_added": "Item added to cart",
        "btn_select": "Select",
        "btn_add_to_cart": "Add to Cart",
        "added_to_cart": "Added to cart.",
        # Cart add notification
        "cart_notify_added": "✅ Product added to your cart.",
        "cart_notify_added_with_details": "✅ {product} added to your cart.\nPrice: {price}",
        "cart_notify_added_with_details_qty": "✅ {product} x{quantity} added to your cart.\nPrice: {price}",
        "btn_continue_shopping": "🛍 Continue Shopping",
        "btn_view_cart": "🧺 View Cart",
        "service_grave_cleaning": "Grave Cleaning",
        "service_grave_cleaning_desc": "Professional grave cleaning and maintenance. We keep the resting place dignified and well-kept.",
        "service_flowers": "Flowers",
        "service_flowers_desc": "Fresh flowers for the grave. We deliver and place them with care.",
        "service_renew_soil": "Renew Soil",
        "service_renew_soil_desc": "Soil renewal and landscaping around the grave area.",
        # Order history
        "order_history_title": "Your Orders",
        "order_history_empty": "You have no orders yet.",
        "order_history_more": "... and {count} more",
        "order_item": "Order #{id} — {status} ({date})",
        "order_photos": "Photos: {count}",
        "no_photos": "No photos",
        # Cart
        "cart_title": "🛒 Your Cart",
        "cart_empty": "Your cart is empty.",
        "cart_place_order": "Place Order",
        "cart_remove": "Remove",
        "cart_clear": "Clear Cart",
        "order_placed": "Order #{order_id} placed successfully. Total: {total}",
        # Order checkout form
        "order_enter_full_name": "Enter your full name:",
        "order_enter_phone": "Share your phone number:",
        "order_select_region": "Select region:",
        "order_select_district": "Select district:",
        "order_select_cemetery": "Select cemetery:",
        "order_enter_deceased": "Enter deceased full name:",
        "order_enter_comment": "Add a comment (optional). Or type /skip:",
        "order_enter_birth_year": "Enter birth year (4 digits, e.g. 1950):",
        "order_enter_death_year": "Enter death year (4 digits, e.g. 2020):",
        "order_invalid_year": "Enter valid year (4 digits, 1900–2100).",
        "order_confirm_title": "Confirm order:",
        "order_confirm_summary": (
            "Region: {region}\nDistrict: {district}\nCemetery: {cemetery}\n"
            "Deceased: {deceased}\nBirth: {birth_year}\nDeath: {death_year}\n\n"
            "Services: {services}\nTotal: {total}"
        ),
        "btn_confirm_order": "Confirm Order",
        "order_cancelled": "Order cancelled.",
        # Order detail
        "order_detail": "Order #{id}\nStatus: {status}\n\n{details}\nTotal: {total}\n\nPhotos: {photo_count}",
        "order_detail_location": "Location: {region}, {district}, {cemetery}",
        "order_detail_deceased": "Deceased: {name} ({birth}–{death})",
        "order_detail_services": "Services:\n{services}",
        "btn_view_photos": "View Photos",
        # Order statuses
        "status_new": "New",
        "status_pending_payment": "Pending Payment",
        "status_payment_review": "Payment Review",
        "status_paid": "Paid",
        "status_in_progress": "In Progress",
        "status_completed": "Completed",
        "status_cancelled": "Cancelled",
        # Payment
        "payment_title": "Payment",
        "payment_select_method": "Select payment method:",
        "payment_cash": "Cash",
        "payment_card": "Card",
        "payment_online": "Online payment",
        "payment_transfer": "Bank transfer",
        "payment_transfer_btn": "Transfer to payment",
        "payment_internal_btn": "🏦 Card (Internal)",
        "payment_visa_btn": "💳 Visa",
        "payment_card_info": "Transfer to this card number (tap to copy):",
        "payment_internal_card_info": "Transfer to this card:",
        "payment_visa_card_info": "Transfer to Visa card:",
        "select_grave_for_order": "Select a grave for this order:",
        "btn_add_new_grave": "➕ Add New Grave",
        "payment_verified": "✅ Your payment has been verified and accepted!\n\n🪦 Cemetery: {cemetery}\n👤 Deceased: {deceased}",
        "payment_not_verified": "❌ Your payment was not verified. Please try again or contact support.\n\n🪦 Cemetery: {cemetery}\n👤 Deceased: {deceased}",
        "order_taken_notify": "✅ Your order has been accepted by our team!\n\n⏰ Photos of completed work will be sent within 3 hours.",
        "order_completed_notify": "🎉 Work completed!\n\nPhotos of the completed work are attached above. Thank you for using our service!",
        "feedback_request": "📊 How was the service?\n\nPlease rate the completed work:",
        "feedback_reason_prompt": "😔 We're sorry the service didn't meet your expectations.\n\nPlease write why you were not satisfied so we can improve and redo the work:",
        "feedback_reason_received": "✅ Thank you for your feedback!\n\nYour complaint has been recorded. The order will be reassigned to another worker for a redo.",
        "payment_send_receipt": "After payment, send a screenshot of your receipt here.",
        "payment_confirm_btn": "✓ Confirm",
        "payment_reject_btn": "✗ Reject",
        "payment_upload_receipt": "Please upload a screenshot of your payment receipt:",
        "payment_receipt_received": "Receipt received. Your order is under review.",
        "payment_confirmed": "✅ Your payment for order #{order_id} has been confirmed. Thank you!",
        "payment_rejected": "❌ Your payment for order #{order_id} was rejected. Please contact support.",
        "btn_proceed_to_payment": "Proceed to Payment",
        # Subscriptions
        "subscriptions_title": "Subscription Plans",
        "subscriptions_info": (
            "📋 Monthly subscription plans include:\n\n"
            "• 4 cleanings per month\n"
            "• Automatic recurring service\n"
            "• Photo report included after each visit\n\n"
            "Contact support for more details."
        ),
        # Complaints
        "complaints_prompt": "Please write your complaint or suggestion. Your message will be sent to our team.",
        "complaints_sent": "Thank you. Your message has been forwarded to our team.",
        "complaints_cancel": "Cancelled.",
        # Support
        "support_prompt": "Please write your message. Our support team will respond as soon as possible.",
        "support_sent": "Thank you. Your message has been sent to support.",
        "support_cancel": "Cancelled.",
        "support_link_message": "Click the button below to contact our support team:",
        "support_link_not_configured": "Support link is not configured. Please contact the administrator.",
        # Rating
        "rating_prompt": "Select an order to rate:",
        "rating_select_order": "Select a completed order to rate:",
        "rating_prompt_like_dislike": "How would you rate our work?",
        "rating_photos_caption": "Photos of completed work:",
        "rating_comment_prompt": "Add a comment (optional). Or press Skip:",
        "rating_skip_comment": "Skip",
        "rating_thanks": "Thank you for your feedback!",
        "rating_already": "You have already rated this order.",
        "rating_like": "👍 Like",
        "rating_dislike": "👎 Dislike",
        "no_orders_to_rate": "You have no completed orders to rate yet.",
        # About
        "about_title": "About Us",
        "about_content": (
            "🏛 Grave Care Service\n\n"
            "Our mission is to provide dignified and respectful care for graves and memorial sites.\n\n"
            "How we work:\n"
            "• You choose a service (cleaning, flowers, soil renewal)\n"
            "• We schedule and perform the work\n"
            "• You receive a photo report upon completion\n"
            "• You can rate our work and stay in touch via support\n\n"
            "We are here to help. Contact us anytime."
        ),
        # User Submission Flow
        "submission_welcome": "Hello {nickname} 👋\n\nWelcome to our service!",
        "submission_enter_name": "Please enter your full name:",
        "submission_enter_phone": "Please share your phone number:",
        "submission_select_relationship": "Select your relationship:",
        "submission_send_photo_1": "📸 Please send the FIRST photo:",
        "submission_send_photo_2": "📸 Great! Now send the SECOND photo:",
        "submission_photo_error": "❌ Please send a PHOTO, not text.\n\nTap the 📎 button and select a photo from your gallery.",
        "submission_photo_file_error": "❌ Please send a PHOTO, not a file.\n\nMake sure to send it as a photo, not as a document.",
        "submission_success": "✅ Thank you! Your submission has been received.",
        "submission_channel_caption": (
            "📥 New User Submission\n\n"
            "👤 Name: {name}\n"
            "🔗 Username: {username}\n"
            "📞 Phone: {phone}\n"
            "👨‍👩‍👧 Relationship: {relationship}"
        ),
        # Relationship options
        "rel_mother": "Mother",
        "rel_father": "Father",
        "rel_grandmother": "Grandmother",
        "rel_grandfather": "Grandfather",
        "rel_brother": "Brother",
        "rel_sister": "Sister",
        "rel_uncle": "Uncle",
        "rel_aunt": "Aunt",
        "rel_spouse": "Spouse",
        "rel_sibling": "Sibling",
        "rel_child": "Child",
        "rel_relative": "Relative",
        "rel_friend": "Friend",
        "rel_other": "Other",
    },
    "ru": {
        "welcome": "Добро пожаловать в сервис ухода за могилами.\nВыберите язык:",
        "welcome_short": "🪦 <b>ДОБАВИТЬ МОГИЛУ</b>\n\nВведите информацию о вашем усопшем близком.\nЭта информация нужна для оформления заказа.",
        "welcome_back": "Здравствуйте, {name}! С возвращением. Выберите услугу из меню.",
        "choose_language": "Выберите язык:",
        "language_selected": "Язык выбран.",
        "btn_change_language": "Изменить язык",
        "registration_required": "👋 Добро пожаловать!\n\nВведите ваше имя:",
        "registration_phone": "Теперь отправьте номер телефона (нажмите кнопку или введите вручную):",
        "registration_complete": "✅ Спасибо, {name}!\n\n🪦 Теперь добавьте могилу, за которой хотите ухаживать:",
        "add_grave_first": "Сначала добавьте могилу, которую хотите убрать.",
        "profile_saved": "Профиль сохранён.",
        "main_menu": "Главное меню",
        "enter_full_name": "Введите ваше полное имя:",
        "enter_phone": "Отправьте номер телефона (нажмите кнопку):",
        "invalid_name": "Имя должно содержать минимум 2 символа. Попробуйте снова.",
        "invalid_phone": "Некорректный номер телефона. Попробуйте снова.",
        "my_profile": "📋 Ваш профиль:\n\nИмя: {full_name}\nТелефон: {phone_number}\nЯзык: {language}",
        "profile_graves_title": "Сохранённые могилы:",
        "profile_graves_empty": "Пока нет сохранённых могил.",
        "profile_grave_item": "{num}. {name}\n   Родство: {relationship}\n   Кладбище: {cemetery}\n   Рождение: {birth} | Смерть: {death}",
        "grave_enter_region": "Выберите регион:",
        "grave_enter_district": "Выберите район:",
        "grave_enter_cemetery": "Выберите кладбище:",
        "grave_enter_deceased": "Введите полное имя умершего:",
        "grave_enter_birth_choice": "Дата рождения — точная или приблизительная?",
        "grave_enter_birth_year": "Введите год рождения (4 цифры, напр. 1950):",
        "grave_enter_birth_year_only": "Введите только год рождения (4 цифры, напр. 1950):",
        "grave_enter_birth_month": "Введите месяц рождения (1-12):",
        "grave_enter_death_choice": "Дата смерти — точная или приблизительная?",
        "grave_dates_choice": "Даты рождения и смерти точные?",
        "grave_enter_death_year": "Введите год смерти (4 цифры, напр. 2020):",
        "grave_enter_death_year_only": "Введите только год смерти (4 цифры, напр. 2020):",
        "grave_enter_death_month": "Введите месяц смерти (1-12):",
        "grave_enter_relationship": "Выберите степень родства:",
        "grave_invalid_month": "Введите месяц от 1 до 12.",
        "btn_exact": "Точно",
        "btn_approximate": "Приблизительно",
        "grave_added": "Могила успешно добавлена.",
        "grave_cancelled": "Отменено.",
        "my_graves_title": "Ваши сохранённые могилы:",
        "my_graves_empty": "У вас пока нет сохранённых могил. Используйте Добавить могилу.",
        "btn_view_profile": "Просмотр профиля",
        "btn_update_profile": "Изменить профиль",
        "btn_services": "Услуги",
        "btn_flowers": "Цветы",
        "btn_cart": "Корзина",
        "btn_profile": "Профиль",
        "btn_share_phone": "📱 Отправить телефон",
        "btn_order_history": "История заказов",
        "btn_subscriptions": "Подписки",
        "btn_complaints": "Жалобы и предложения",
        "btn_support": "Связаться с поддержкой",
        "btn_rating": "Оценить работу",
        "btn_about": "О нас",
        "btn_back": "⬅️ Назад",
        "btn_cancel": "❌ Отмена",
        "btn_skip": "Пропустить",
        "btn_add_grave": "Добавить могилу",
        "btn_my_graves": "Мои могилы",
        "btn_main_menu": "◀️ Главное меню",
        "services_title": "Наши услуги",
        "btn_cleaning": "Уборка",
        "btn_basic_cleaning": "Базовая уборка",
        "btn_deep_cleaning": "Глубокая уборка",
        "btn_full_maintenance": "Полное обслуживание",
        "btn_plant_flowers": "Посадка цветов",
        "btn_watering_service": "Полив",
        "btn_seasonal_care": "Сезонный уход",
        "section_grave_cleaning": "Уборка могил",
        "section_flowers": "Цветы",
        "section_grave_renewal": "Обновление могилы",
        "flower_catalog": "Каталог цветов",
        "flower_menu_title": "🌸 Меню цветов",
        "flower_category_planted": "Цветы, посаженные вокруг могилы",
        "flower_category_placed": "Цветы, размещённые на могиле",
        "flower_order_first_name": "Введите имя:",
        "flower_order_last_name": "Введите фамилию:",
        "flower_order_birth_year": "Введите год рождения (4 цифры, напр. 1950):",
        "flower_order_death_year": "Введите год смерти (4 цифры, напр. 2020):",
        "flower_confirm_summary": "Товары:\n{items}\n\nИтого: {total}",
        "flower_proceed_to_payment": "Перейти к оплате",
        "flower_item_added": "Товар добавлен в корзину",
        "btn_select": "Выбрать",
        "btn_add_to_cart": "Добавить в корзину",
        "added_to_cart": "Добавлено в корзину.",
        "cart_notify_added": "✅ Товар добавлен в корзину.",
        "cart_notify_added_with_details": "✅ {product} добавлен в корзину.\nЦена: {price}",
        "cart_notify_added_with_details_qty": "✅ {product} x{quantity} добавлено в корзину.\nЦена: {price}",
        "btn_continue_shopping": "🛍 Продолжить покупки",
        "btn_view_cart": "🧺 Корзина",
        "service_grave_cleaning": "Уборка могил",
        "service_grave_cleaning_desc": "Профессиональная уборка и уход за могилами. Поддерживаем достойный вид места упокоения.",
        "service_flowers": "Цветы",
        "service_flowers_desc": "Свежие цветы для могилы. Доставляем и размещаем с заботой.",
        "service_renew_soil": "Обновление грунта",
        "service_renew_soil_desc": "Обновление почвы и озеленение вокруг могилы.",
        "order_history_title": "Ваши заказы",
        "order_history_empty": "У вас пока нет заказов.",
        "order_history_more": "... и ещё {count}",
        "order_item": "Заказ #{id} — {status} ({date})",
        "order_photos": "Фото: {count}",
        "no_photos": "Нет фото",
        "cart_title": "🛒 Ваша корзина",
        "cart_empty": "Корзина пуста.",
        "cart_place_order": "Оформить заказ",
        "cart_remove": "Удалить",
        "cart_clear": "Очистить корзину",
        "order_placed": "Заказ #{order_id} оформлен. Итого: {total}",
        "order_select_region": "Выберите регион:",
        "order_select_district": "Выберите район:",
        "order_select_cemetery": "Выберите кладбище:",
        "order_enter_deceased": "Введите полное имя умершего:",
        "order_enter_birth_year": "Введите год рождения (4 цифры, например 1950):",
        "order_enter_death_year": "Введите год смерти (4 цифры, например 2020):",
        "order_invalid_year": "Введите корректный год (4 цифры, 1900–2100).",
        "order_confirm_title": "Подтвердите заказ:",
        "order_confirm_summary": (
            "Регион: {region}\nРайон: {district}\nКладбище: {cemetery}\n"
            "Умерший: {deceased}\nРождение: {birth_year}\nСмерть: {death_year}\n\n"
            "Услуги: {services}\nИтого: {total}"
        ),
        "btn_confirm_order": "Подтвердить заказ",
        "order_cancelled": "Заказ отменён.",
        "order_detail": "Заказ #{id}\nСтатус: {status}\n\n{details}\nИтого: {total}\n\nФото: {photo_count}",
        "order_detail_location": "Место: {region}, {district}, {cemetery}",
        "order_detail_deceased": "Умерший: {name} ({birth}–{death})",
        "order_detail_services": "Услуги:\n{services}",
        "btn_view_photos": "Смотреть фото",
        "status_new": "Новый",
        "status_pending_payment": "Ожидание оплаты",
        "status_payment_review": "Проверка оплаты",
        "status_paid": "Оплачен",
        "status_in_progress": "В работе",
        "status_completed": "Выполнен",
        "status_cancelled": "Отменён",
        "payment_title": "Оплата",
        "payment_select_method": "Выберите способ оплаты:",
        "payment_cash": "Наличные",
        "payment_card": "Карта",
        "payment_online": "Онлайн оплата",
        "payment_transfer": "Банковский перевод",
        "payment_transfer_btn": "Перейти к оплате",
        "payment_internal_btn": "🏦 Карта (Внутренний)",
        "payment_visa_btn": "💳 Visa",
        "payment_card_info": "Переведите на эту карту (нажмите, чтобы скопировать):",
        "payment_internal_card_info": "Переведите на эту карту:",
        "payment_visa_card_info": "Переведите на карту Visa:",
        "select_grave_for_order": "Выберите могилу для этого заказа:",
        "btn_add_new_grave": "➕ Добавить новую могилу",
        "payment_verified": "✅ Ваш платёж подтверждён и принят!\n\n🪦 Кладбище: {cemetery}\n👤 Умерший: {deceased}",
        "payment_not_verified": "❌ Ваш платёж не подтверждён. Попробуйте снова или обратитесь в поддержку.\n\n🪦 Кладбище: {cemetery}\n👤 Умерший: {deceased}",
        "order_taken_notify": "✅ Ваш заказ принят нашей командой!\n\n⏰ Фотографии выполненной работы будут отправлены в течение 3 часов.",
        "order_completed_notify": "🎉 Работа выполнена!\n\nФотографии выполненной работы прикреплены выше. Спасибо, что пользуетесь нашим сервисом!",
        "feedback_request": "📊 Как вам обслуживание?\n\nПожалуйста, оцените выполненную работу:",
        "feedback_reason_prompt": "😔 Нам жаль, что услуга не оправдала ваших ожиданий.\n\nПожалуйста, напишите, почему вы остались недовольны, чтобы мы могли улучшить работу и переделать её:",
        "feedback_reason_received": "✅ Спасибо за ваш отзыв!\n\nВаша жалоба записана. Заказ будет передан другому работнику для переделки.",
        "payment_send_receipt": "После оплаты отправьте скриншот квитанции сюда.",
        "payment_confirm_btn": "✓ Подтвердить",
        "payment_reject_btn": "✗ Отклонить",
        "payment_upload_receipt": "Загрузите скриншот квитанции об оплате:",
        "payment_receipt_received": "Квитанция получена. Заказ на проверке.",
        "payment_confirmed": "✅ Ваша оплата заказа #{order_id} подтверждена. Спасибо!",
        "payment_rejected": "❌ Ваша оплата заказа #{order_id} отклонена. Обратитесь в поддержку.",
        "btn_proceed_to_payment": "Перейти к оплате",
        "order_enter_full_name": "Введите ваше полное имя:",
        "order_enter_phone": "Отправьте номер телефона:",
        "order_enter_comment": "Добавьте комментарий (необязательно). Или /skip:",
        "subscriptions_title": "Планы подписки",
        "subscriptions_info": (
            "📋 Ежемесячные планы включают:\n\n"
            "• 4 уборки в месяц\n"
            "• Автоматическое повторяющееся обслуживание\n"
            "• Фотоотчёт после каждого визита\n\n"
            "Свяжитесь с поддержкой для уточнения деталей."
        ),
        "complaints_prompt": "Напишите вашу жалобу или предложение. Сообщение будет отправлено нашей команде.",
        "complaints_sent": "Спасибо. Ваше сообщение отправлено нашей команде.",
        "complaints_cancel": "Отменено.",
        "support_prompt": "Напишите ваше сообщение. Наша команда поддержки ответит как можно скорее.",
        "support_sent": "Спасибо. Ваше сообщение отправлено в поддержку.",
        "support_cancel": "Отменено.",
        "support_link_message": "Нажмите кнопку ниже, чтобы связаться с нашей службой поддержки:",
        "support_link_not_configured": "Ссылка поддержки не настроена. Обратитесь к администратору.",
        "rating_prompt": "Выберите заказ для оценки:",
        "rating_select_order": "Выберите выполненный заказ для оценки:",
        "rating_prompt_like_dislike": "Как вы оцениваете нашу работу?",
        "rating_photos_caption": "Фото выполненной работы:",
        "rating_comment_prompt": "Добавьте комментарий (необязательно). Или нажмите Пропустить:",
        "rating_skip_comment": "Пропустить",
        "rating_thanks": "Спасибо за отзыв!",
        "rating_already": "Вы уже оценили этот заказ.",
        "rating_like": "👍 Нравится",
        "rating_dislike": "👎 Не нравится",
        "no_orders_to_rate": "У вас пока нет выполненных заказов для оценки.",
        "about_title": "О нас",
        "about_content": (
            "🏛 Сервис ухода за могилами\n\n"
            "Наша миссия — обеспечивать достойный и уважительный уход за могилами и памятными местами.\n\n"
            "Как мы работаем:\n"
            "• Вы выбираете услугу (уборка, цветы, обновление грунта)\n"
            "• Мы планируем и выполняем работу\n"
            "• Вы получаете фотоотчёт по завершении\n"
            "• Вы можете оценить нашу работу и связаться с нами через поддержку\n\n"
            "Мы всегда готовы помочь. Свяжитесь с нами в любое время."
        ),
        # User Submission Flow
        "submission_welcome": "Здравствуйте {nickname} 👋\n\nДобро пожаловать в наш сервис!",
        "submission_enter_name": "Введите ваше полное имя:",
        "submission_enter_phone": "Отправьте ваш номер телефона:",
        "submission_select_relationship": "Выберите степень родства:",
        "submission_send_photo_1": "📸 Отправьте ПЕРВОЕ фото:",
        "submission_send_photo_2": "📸 Отлично! Теперь отправьте ВТОРОЕ фото:",
        "submission_photo_error": "❌ Пожалуйста, отправьте ФОТО, а не текст.\n\nНажмите кнопку 📎 и выберите фото из галереи.",
        "submission_photo_file_error": "❌ Пожалуйста, отправьте ФОТО, а не файл.\n\nУбедитесь, что отправляете как фото, а не как документ.",
        "submission_success": "✅ Спасибо! Ваша заявка получена.",
        "submission_channel_caption": (
            "📥 Новая заявка\n\n"
            "👤 Имя: {name}\n"
            "🔗 Пользователь: {username}\n"
            "📞 Телефон: {phone}\n"
            "👨‍👩‍👧 Родство: {relationship}"
        ),
        # Relationship options
        "rel_mother": "Мать",
        "rel_father": "Отец",
        "rel_grandmother": "Бабушка",
        "rel_grandfather": "Дедушка",
        "rel_brother": "Брат",
        "rel_sister": "Сестра",
        "rel_uncle": "Дядя",
        "rel_aunt": "Тётя",
        "rel_spouse": "Супруг(а)",
        "rel_sibling": "Брат/Сестра",
        "rel_child": "Ребёнок",
        "rel_relative": "Родственник",
        "rel_friend": "Друг",
        "rel_other": "Другое",
    },
    "uz": {
        "welcome": "Qabr parvarish xizmatiga xush kelibsiz.\nTilni tanlang:",
        "welcome_short": "🪦 <b>QABR QO'SHISH</b>\n\nQuyida marhum yaqiningiz haqida ma'lumot kiriting.\nBu ma'lumotlar buyurtma berish uchun kerak bo'ladi.",
        "welcome_back": "Assalomu alaykum, {name}! Xush kelibsiz. Quyidagi menyudan xizmatni tanlang.",
        "choose_language": "Tilni tanlang:",
        "language_selected": "Til tanlandi.",
        "btn_change_language": "Tilni o'zgartirish",
        "registration_required": "👋 Xush kelibsiz!\n\nIsmingizni kiriting:",
        "registration_phone": "Endi telefon raqamingizni yuboring (tugmani bosing yoki yozing):",
        "registration_complete": "✅ Rahmat, {name}!\n\n🪦 Endi parvarish qilmoqchi bo'lgan qabrni ro'yxatga qo'shing:",
        "add_grave_first": "Avval tozalatmoqchi bo'lgan qabrni qo'shing.",
        "profile_saved": "Profil saqlandi.",
        "main_menu": "Asosiy menyu",
        "enter_full_name": "To'liq ismingizni kiriting:",
        "enter_phone": "Telefon raqamingizni yuboring (tugmani bosing):",
        "invalid_name": "Ism kamida 2 belgidan iborat bo'lishi kerak. Qaytadan urinib ko'ring.",
        "invalid_phone": "Noto'g'ri raqam. Qaytadan urinib ko'ring.",
        "my_profile": "📋 Profilingiz:\n\nIsm: {full_name}\nTelefon: {phone_number}\nTil: {language}",
        "profile_graves_title": "Saqlangan qabrlari:",
        "profile_graves_empty": "Hali saqlangan qabr yo'q.",
        "profile_grave_item": "{num}. {name}\n   Qarindoshlik: {relationship}\n   Qabriston: {cemetery}\n   Tug'ilgan: {birth} | Vafot: {death}",
        "grave_enter_region": "📍 Viloyatni tanlang:",
        "grave_enter_district": "📍 Tumanni tanlang:",
        "grave_enter_cemetery": "🏛 Qabristonni tanlang:",
        "grave_enter_deceased": "👤 Marhumning ismini yozing:",
        "grave_enter_birth_choice": "📅 Tug'ilgan yili aniqmi?",
        "grave_enter_birth_year": "📅 Tug'ilgan yili? (masalan: 1950)",
        "grave_enter_birth_year_only": "📅 Tug'ilgan yili? (masalan: 1950)",
        "grave_enter_birth_month": "📅 Tug'ilgan oyi? (1-12)",
        "grave_enter_death_choice": "📅 Vafot yili aniqmi?",
        "grave_dates_choice": "📅 Tug'ilgan va vafot sanasi aniqmi?",
        "grave_enter_death_year": "📅 Vafot yili? (masalan: 2020)",
        "grave_enter_death_year_only": "📅 Vafot yili? (masalan: 2020)",
        "grave_enter_death_month": "📅 Vafot oyi? (1-12)",
        "grave_enter_relationship": "👨‍👩‍👧 Sizga kim bo'ladi?",
        "grave_invalid_month": "To'g'ri oy kiriting (1-12).",
        "btn_exact": "Aniq",
        "btn_approximate": "Taxminan",
        "grave_added": "✅ Qabr muvaffaqiyatli saqlandi!\n\nEndi quyidagi menyudan xizmat tanlashingiz mumkin:",
        "grave_cancelled": "Bekor qilindi.",
        "my_graves_title": "Saqlangan qabrlaringiz:",
        "my_graves_empty": "Sizda hali saqlangan qabr yo'q. Qo'shish uchun Qabr qo'shish tugmasini bosing.",
        "btn_view_profile": "Profilni ko'rish",
        "btn_update_profile": "Profilni yangilash",
        "btn_services": "Xizmatlar",
        "btn_flowers": "Gullar",
        "btn_cart": "Savat",
        "btn_profile": "Profil",
        "btn_share_phone": "📱 Telefon yuborish",
        "btn_order_history": "Buyurtmalar tarixi",
        "btn_subscriptions": "Obunalar",
        "btn_complaints": "Shikoyat va takliflar",
        "btn_support": "Qo'llab-quvvatlash bilan bog'lanish",
        "btn_rating": "Ishni baholash",
        "btn_about": "Biz haqimizda",
        "btn_back": "⬅️ Orqaga",
        "btn_cancel": "❌ Bekor qilish",
        "btn_skip": "O'tkazib yuborish",
        "btn_add_grave": "Qabr qo'shish",
        "btn_my_graves": "Mening qabrlari",
        "btn_main_menu": "◀️ Asosiy menyu",
        "services_title": "🛠 <b>XIZMATLAR</b>\n\nQuyidagi xizmatlardan birini tanlang:",
        "btn_cleaning": "Tozalash",
        "btn_basic_cleaning": "Asosiy tozalash",
        "btn_deep_cleaning": "Chuqur tozalash",
        "btn_full_maintenance": "To'liq parvarish",
        "btn_plant_flowers": "Gul ekish",
        "btn_watering_service": "Suv berish",
        "btn_seasonal_care": "Mavsumiy parvarish",
        "section_grave_cleaning": "Qabr tozalash",
        "section_flowers": "Gullar",
        "section_grave_renewal": "Qabr yangilash",
        "flower_catalog": "Gullar katalogi",
        "flower_menu_title": "🌸 Gullar menyusi",
        "flower_category_planted": "Qabr atrofida ekilgan gullar",
        "flower_category_placed": "Qabr ustiga qo'yilgan gullar",
        "flower_order_first_name": "Ismingizni kiriting:",
        "flower_order_last_name": "Familiyangizni kiriting:",
        "flower_order_birth_year": "Tug'ilgan yilni kiriting (4 raqam, masalan 1950):",
        "flower_order_death_year": "Vafot yilini kiriting (4 raqam, masalan 2020):",
        "flower_confirm_summary": "Mahsulotlar:\n{items}\n\nJami: {total}",
        "flower_proceed_to_payment": "To'lovga o'tish",
        "flower_item_added": "Mahsulot savatga qo'shildi",
        "btn_select": "Tanlash",
        "btn_add_to_cart": "Savatga qo'shish",
        "added_to_cart": "Savatga qo'shildi.",
        "cart_notify_added": "✅ Mahsulot savatga qo'shildi.",
        "cart_notify_added_with_details": "✅ {product} savatga qo'shildi.\nNarx: {price}",
        "cart_notify_added_with_details_qty": "✅ {product} x{quantity} savatga qo'shildi.\nNarx: {price}",
        "btn_continue_shopping": "🛍 Xaridni davom ettirish",
        "btn_view_cart": "🧺 Savat",
        "service_grave_cleaning": "Qabr tozalash",
        "service_grave_cleaning_desc": "Professional qabr tozalash va parvarish. Joyni qadrli va chiroyli saqlaymiz.",
        "service_flowers": "Gullar",
        "service_flowers_desc": "Qabr uchun yangi gullar. Yetkazib beramiz va g'amxo'rlik bilan joylashtiramiz.",
        "service_renew_soil": "Tuproq yangilash",
        "service_renew_soil_desc": "Qabr atrofidagi tuproq yangilash va landshaft ishlari.",
        "order_history_title": "Buyurtmalaringiz",
        "order_history_empty": "Sizda hali buyurtmalar yo'q.",
        "order_history_more": "... va yana {count} ta",
        "order_item": "Buyurtma #{id} — {status} ({date})",
        "order_photos": "Rasmlar: {count}",
        "no_photos": "Rasmlar yo'q",
        "cart_title": "🛒 Savatingiz",
        "cart_empty": "Savat bo'sh.",
        "cart_place_order": "Buyurtma berish",
        "cart_remove": "O'chirish",
        "cart_clear": "Savatni tozalash",
        "order_placed": "Buyurtma #{order_id} qabul qilindi. Jami: {total}",
        "order_select_region": "Viloyatni tanlang:",
        "order_select_district": "Tumanni tanlang:",
        "order_select_cemetery": "Qabristonni tanlang:",
        "order_enter_deceased": "Vafot etgan shaxsning to'liq ismini kiriting:",
        "order_enter_birth_year": "Tug'ilgan yilni kiriting (4 raqam, masalan 1950):",
        "order_enter_death_year": "Vafot yilini kiriting (4 raqam, masalan 2020):",
        "order_invalid_year": "To'g'ri yil kiriting (4 raqam, 1900–2100).",
        "order_confirm_title": "Buyurtmani tasdiqlang:",
        "order_confirm_summary": (
            "Viloyat: {region}\nTuman: {district}\nQabriston: {cemetery}\n"
            "Vafot etgan: {deceased}\nTug'ilgan: {birth_year}\nVafot: {death_year}\n\n"
            "Xizmatlar: {services}\nJami: {total}"
        ),
        "btn_confirm_order": "Buyurtmani tasdiqlash",
        "order_cancelled": "Buyurtma bekor qilindi.",
        "order_detail": "Buyurtma #{id}\nHolat: {status}\n\n{details}\nJami: {total}\n\nRasmlar: {photo_count}",
        "order_detail_location": "Joy: {region}, {district}, {cemetery}",
        "order_detail_deceased": "Vafot etgan: {name} ({birth}–{death})",
        "order_detail_services": "Xizmatlar:\n{services}",
        "btn_view_photos": "Rasmlarni ko'rish",
        "status_new": "Yangi",
        "status_pending_payment": "To'lov kutilmoqda",
        "status_payment_review": "To'lov tekshirilmoqda",
        "status_paid": "To'langan",
        "status_in_progress": "Jarayonda",
        "status_completed": "Bajarildi",
        "status_cancelled": "Bekor qilindi",
        "payment_title": "To'lov",
        "payment_select_method": "To'lov usulini tanlang:",
        "payment_cash": "Naqd",
        "payment_card": "Karta",
        "payment_online": "Onlayn to'lov",
        "payment_transfer": "Bank o'tkazmasi",
        "payment_transfer_btn": "To'lovga o'tkazish",
        "payment_internal_btn": "🏦 Karta (Ichki)",
        "payment_visa_btn": "💳 Visa",
        "payment_card_info": "Ushbu karta raqamiga o'tkazing (nusxa olish uchun bosing):",
        "payment_internal_card_info": "Ushbu kartaga o'tkazing:",
        "payment_visa_card_info": "Visa kartaga o'tkazing:",
        "select_grave_for_order": "Buyurtma uchun qabrni tanlang:",
        "btn_add_new_grave": "➕ Yangi qabr qo'shish",
        "payment_verified": "✅ To'lovingiz tasdiqlandi va qabul qilindi!\n\n🪦 Qabriston: {cemetery}\n👤 Marhum: {deceased}",
        "payment_not_verified": "❌ To'lovingiz tasdiqlanmadi. Qaytadan urinib ko'ring yoki qo'llab-quvvatlash bilan bog'laning.\n\n🪦 Qabriston: {cemetery}\n👤 Marhum: {deceased}",
        "order_taken_notify": "✅ Buyurtmangiz jamoamiz tomonidan qabul qilindi!\n\n⏰ Bajarilgan ish fotolari 3 soat ichida yuboriladi.",
        "order_completed_notify": "🎉 Ish bajarildi!\n\nBajarilgan ish fotolari yuqorida biriktirilgan. Xizmatimizdan foydalanganingiz uchun rahmat!",
        "feedback_request": "📊 Xizmat qanday bo'ldi?\n\nIltimos, bajarilgan ishni baholang:",
        "feedback_reason_prompt": "😔 Xizmat kutganingizdek bo'lmagani uchun uzr so'raymiz.\n\nIltimos, nima uchun mamnun bo'lmaganingizni yozing, shunda biz ishni yaxshilab qayta bajaramiz:",
        "feedback_reason_received": "✅ Fikringiz uchun rahmat!\n\nShikoyatingiz qayd etildi. Buyurtma qayta bajarish uchun boshqa ishchiga topshiriladi.",
        "payment_send_receipt": "To'lovdan keyin kvitansiya skrinshotini shu yerga yuboring.",
        "payment_confirm_btn": "✓ Tasdiqlash",
        "payment_reject_btn": "✗ Rad etish",
        "payment_upload_receipt": "To'lov kvitansiyasi skrinshotini yuklang:",
        "payment_receipt_received": "Kvitansiya qabul qilindi. Buyurtma tekshirilmoqda.",
        "payment_confirmed": "✅ Buyurtma #{order_id} uchun to'lovingiz tasdiqlandi. Rahmat!",
        "payment_rejected": "❌ Buyurtma #{order_id} uchun to'lovingiz rad etildi. Qo'llab-quvvatlash bilan bog'laning.",
        "btn_proceed_to_payment": "To'lovga o'tish",
        "order_enter_full_name": "To'liq ismingizni kiriting:",
        "order_enter_phone": "Telefon raqamingizni yuboring:",
        "order_enter_comment": "Izoh qo'shing (ixtiyoriy). Yoki /skip:",
        "subscriptions_title": "Obuna rejalari",
        "subscriptions_info": (
            "📋 Oylik obuna rejalari quyidagilarni o'z ichiga oladi:\n\n"
            "• Oyiga 4 marta tozalash\n"
            "• Avtomatik takrorlanuvchi xizmat\n"
            "• Har bir tashrifdan keyin foto hisobot\n\n"
            "Batafsil ma'lumot uchun qo'llab-quvvatlash bilan bog'laning."
        ),
        "complaints_prompt": "Shikoyatingiz yoki taklifingizni yozing. Xabaringiz jamoamizga yuboriladi.",
        "complaints_sent": "Rahmat. Xabaringiz jamoamizga yuborildi.",
        "complaints_cancel": "Bekor qilindi.",
        "support_prompt": "Xabaringizni yozing. Qo'llab-quvvatlash jamoamiz imkon qadar tezroq javob beradi.",
        "support_sent": "Rahmat. Xabaringiz qo'llab-quvvatlashga yuborildi.",
        "support_cancel": "Bekor qilindi.",
        "support_link_message": "Qo'llab-quvvatlash jamoamiz bilan bog'lanish uchun quyidagi tugmani bosing:",
        "support_link_not_configured": "Qo'llab-quvvatlash havolasi sozlanmagan. Administrator bilan bog'laning.",
        "rating_prompt": "Baholash uchun buyurtmani tanlang:",
        "rating_select_order": "Baholash uchun bajarilgan buyurtmani tanlang:",
        "rating_prompt_like_dislike": "Ishimizni qanday baholaysiz?",
        "rating_photos_caption": "Bajarilgan ish fotolari:",
        "rating_comment_prompt": "Izoh qo'shing (ixtiyoriy). Yoki O'tkazib yuborishni bosing:",
        "rating_skip_comment": "O'tkazib yuborish",
        "rating_thanks": "Fikringiz uchun rahmat!",
        "rating_already": "Siz bu buyurtmani allaqachon baholagansiz.",
        "rating_like": "👍 Yoqdi",
        "rating_dislike": "👎 Yoqmadi",
        "no_orders_to_rate": "Baholash uchun bajarilgan buyurtmalaringiz yo'q.",
        "about_title": "Biz haqimizda",
        "about_content": (
            "🏛 Qabr parvarish xizmati\n\n"
            "Bizning vazifamiz — qabrlarni va yodgorlik joylarini qadrli va hurmatli parvarish qilish.\n\n"
            "Qanday ishlaymiz:\n"
            "• Siz xizmatni tanlaysiz (tozalash, gullar, tuproq yangilash)\n"
            "• Biz rejalashtiramiz va ishni bajaramiz\n"
            "• Tugagach foto hisobot olasiz\n"
            "• Ishni baholashingiz va qo'llab-quvvatlash orqali bog'lanishingiz mumkin\n\n"
            "Yordam berishga tayyormiz. Istalgan vaqtda bog'laning."
        ),
        # User Submission Flow
        "submission_welcome": "Assalomu alaykum {nickname} 👋\n\nXizmatimizga xush kelibsiz!",
        "submission_enter_name": "To'liq ismingizni kiriting:",
        "submission_enter_phone": "Telefon raqamingizni yuboring:",
        "submission_select_relationship": "Qarindoshlikni tanlang:",
        "submission_send_photo_1": "📸 BIRINCHI rasmni yuboring:",
        "submission_send_photo_2": "📸 Ajoyib! Endi IKKINCHI rasmni yuboring:",
        "submission_photo_error": "❌ Iltimos, matn emas, RASM yuboring.\n\n📎 tugmasini bosing va galereyadan rasm tanlang.",
        "submission_photo_file_error": "❌ Iltimos, fayl emas, RASM yuboring.\n\nRasmni hujjat sifatida emas, rasm sifatida yuboring.",
        "submission_success": "✅ Rahmat! Arizangiz qabul qilindi.",
        "submission_channel_caption": (
            "📥 Yangi ariza\n\n"
            "👤 Ism: {name}\n"
            "🔗 Foydalanuvchi: {username}\n"
            "📞 Telefon: {phone}\n"
            "👨‍👩‍👧 Qarindoshlik: {relationship}"
        ),
        # Relationship options
        "rel_mother": "Ona",
        "rel_father": "Ota",
        "rel_grandmother": "Buvi",
        "rel_grandfather": "Bobo",
        "rel_brother": "Aka/Uka",
        "rel_sister": "Opa/Singil",
        "rel_uncle": "Tog'a/Amaki",
        "rel_aunt": "Xola/Amma",
        "rel_spouse": "Turmush o'rtog'i",
        "rel_sibling": "Aka/Opa/Uka/Singil",
        "rel_child": "Farzand",
        "rel_relative": "Qarindosh",
        "rel_friend": "Do'st",
        "rel_other": "Boshqa",
    },
}

# Language display names
LANG_NAMES: dict[str, str] = {
    "en": "English",
    "ru": "Русский",
    "uz": "O'zbekcha",
}


def get_text(lang: str, key: str, **kwargs: Any) -> str:
    """Get localized text. Falls back to Russian if key missing."""
    texts = TEXTS.get(lang, TEXTS["ru"])
    s = texts.get(key, TEXTS["ru"].get(key, key))
    if kwargs:
        s = s.format(**kwargs)
    return s


def get_all_button_texts(key: str) -> frozenset[str]:
    """Return all translations for a button key (en, ru, uz). For F.text.in_() filters."""
    return frozenset(
        t for lang in ("en", "ru", "uz")
        for t in (TEXTS[lang].get(key, ""),)
        if t
    )


def get_status_label(lang: str, status: str) -> str:
    """Get localized status label."""
    key = f"status_{status}"
    return get_text(lang, key) if key in TEXTS.get(lang, TEXTS["ru"]) else status
