# Generated by Django 4.2.15 on 2026-03-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("cleaning", "Cleaning"),
                    ("flower", "Flower"),
                    ("other", "Other"),
                ],
                default="cleaning",
                max_length=20,
            ),
        ),
    ]
