# Generated by Django 4.2.15 on 2026-03-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_add_category_to_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="flower",
            name="planting_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Labor cost added automatically when > 0",
                max_digits=10,
                verbose_name="Qo'l haqqi / Planting fee",
            ),
        ),
        migrations.AlterField(
            model_name="flower",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Narxi / Price"
            ),
        ),
    ]
