# Generated by Django 4.2.15 on 2026-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_add_planting_fee_to_flower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flower",
            options={
                "ordering": ["name"],
                "verbose_name": "Gul / Flower",
                "verbose_name_plural": "Gullar / Flowers",
            },
        ),
        migrations.AddField(
            model_name="flower",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Yetkazib berish narxi / Delivery cost",
                max_digits=10,
                verbose_name="Dastafka narxi / Delivery fee",
            ),
        ),
        migrations.AddField(
            model_name="flower",
            name="is_plantable",
            field=models.BooleanField(
                default=False,
                help_text="Agar gul ekiladigan bo'lsa belgilang",
                verbose_name="Ekiladigan gul / Plantable",
            ),
        ),
        migrations.AlterField(
            model_name="flower",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nomi / Name"),
        ),
        migrations.AlterField(
            model_name="flower",
            name="planting_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Faqat ekiladigan gullar uchun / Only for plantable flowers",
                max_digits=10,
                verbose_name="Ekish narxi / Planting fee",
            ),
        ),
    ]
