# Generated by Django 4.2.15 on 2026-03-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_add_delivery_and_plantable_to_flower"),
    ]

    operations = [
        migrations.AddField(
            model_name="flower",
            name="description_en",
            field=models.TextField(
                blank=True, default="", verbose_name="Description (English)"
            ),
        ),
        migrations.AddField(
            model_name="flower",
            name="description_ru",
            field=models.TextField(
                blank=True, default="", verbose_name="Описание (Русский)"
            ),
        ),
        migrations.AddField(
            model_name="flower",
            name="description_uz",
            field=models.TextField(
                blank=True, default="", verbose_name="Tavsif (O'zbekcha)"
            ),
        ),
        migrations.AddField(
            model_name="flower",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Name (English)"
            ),
        ),
        migrations.AddField(
            model_name="flower",
            name="name_ru",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Название (Русский)",
            ),
        ),
        migrations.AddField(
            model_name="flower",
            name="name_uz",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Nom (O'zbekcha)"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(
                blank=True, default="", verbose_name="Description (English)"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="description_ru",
            field=models.TextField(
                blank=True, default="", verbose_name="Описание (Русский)"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="description_uz",
            field=models.TextField(
                blank=True, default="", verbose_name="Tavsif (O'zbekcha)"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Name (English)"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="name_ru",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Название (Русский)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="name_uz",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Nom (O'zbekcha)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nom (asosiy)"),
        ),
    ]
