# Generated by Django 4.2.15 on 2026-03-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_flower"),
        ("catalog", "0005_add_multilang_to_service_flower"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Flower",
        ),
    ]
